<?php

/*VALIDACIONES - VALIDACIONES - VALIDACIONES - VALIDACIONES - VALIDACIONES*/
/*VALIDACIONES - VALIDACIONES - VALIDACIONES - VALIDACIONES - VALIDACIONES*/

/*CREAR REGISTRO - CREAR REGISTRO - CREAR REGISTRO - CREAR REGISTRO - CREAR REGISTRO -*/
/*CREAR REGISTRO - CREAR REGISTRO - CREAR REGISTRO - CREAR REGISTRO - CREAR REGISTRO -*/

/*SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION*/
/*SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION SESSION*/

/*COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES*/
/*COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES COOKIES*/

/*CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD*/
/*CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD CRUD*/